In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
loandf = pd.read_csv('/content/drive/MyDrive/loan.csv')

<ipython-input-3-3770e46ff65c>:1: DtypeWarning: Columns (19,47,55,112,123,124,125,128,129,130,133,139,140,141) have mixed types. Specify dtype option on import or set low_memory=False.
  loandf = pd.read_csv('/content/drive/MyDrive/loan.csv')

In [4]:
pd.set_option('display.max_info_columns', 200)

In [5]:
loandf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260668 entries, 0 to 2260667
Data columns (total 145 columns):
 #    Column                                      Dtype
---   ------                                      -----
 0    id                                          float64
 1    member_id                                   float64
 2    loan_amnt                                   int64
 3    funded_amnt                                 int64
 4    funded_amnt_inv                             float64
 5    term                                        object
 6    int_rate                                    float64
 7    installment                                 float64
 8    grade                                       object
 9    sub_grade                                   object
 10   emp_title                                   object
 11   emp_length                                  object
 12   home_ownership                              object
 13   annual_inc                                  float64
 14   verification_status                         object
 15   issue_d                                     object
 16   loan_status                                 object
 17   pymnt_plan                                  object
 18   url                                         float64
 19   desc                                        object
 20   purpose                                     object
 21   title                                       object
 22   zip_code                                    object
 23   addr_state                                  object
 24   dti                                         float64
 25   delinq_2yrs                                 float64
 26   earliest_cr_line                            object
 27   inq_last_6mths                              float64
 28   mths_since_last_delinq                      float64
 29   mths_since_last_record                      float64
 30   open_acc                                    float64
 31   pub_rec                                     float64
 32   revol_bal                                   int64
 33   revol_util                                  float64
 34   total_acc                                   float64
 35   initial_list_status                         object
 36   out_prncp                                   float64
 37   out_prncp_inv                               float64
 38   total_pymnt                                 float64
 39   total_pymnt_inv                             float64
 40   total_rec_prncp                             float64
 41   total_rec_int                               float64
 42   total_rec_late_fee                          float64
 43   recoveries                                  float64
 44   collection_recovery_fee                     float64
 45   last_pymnt_d                                object
 46   last_pymnt_amnt                             float64
 47   next_pymnt_d                                object
 48   last_credit_pull_d                          object
 49   collections_12_mths_ex_med                  float64
 50   mths_since_last_major_derog                 float64
 51   policy_code                                 int64
 52   application_type                            object
 53   annual_inc_joint                            float64
 54   dti_joint                                   float64
 55   verification_status_joint                   object
 56   acc_now_delinq                              float64
 57   tot_coll_amt                                float64
 58   tot_cur_bal                                 float64
 59   open_acc_6m                                 float64
 60   open_act_il                                 float64
 61   open_il_12m                                 float64
 62   open_il_24m                                 float64
 63   mths_since_rcnt_il                          float64
 64   total_bal_il                                float64
 65   il_util                                     float64
 66   open_rv_12m                                 float64
 67   open_rv_24m                                 float64
 68   max_bal_bc                                  float64
 69   all_util                                    float64
 70   total_rev_hi_lim                            float64
 71   inq_fi                                      float64
 72   total_cu_tl                                 float64
 73   inq_last_12m                                float64
 74   acc_open_past_24mths                        float64
 75   avg_cur_bal                                 float64
 76   bc_open_to_buy                              float64
 77   bc_util                                     float64
 78   chargeoff_within_12_mths                    float64
 79   delinq_amnt                                 float64
 80   mo_sin_old_il_acct                          float64
 81   mo_sin_old_rev_tl_op                        float64
 82   mo_sin_rcnt_rev_tl_op                       float64
 83   mo_sin_rcnt_tl                              float64
 84   mort_acc                                    float64
 85   mths_since_recent_bc                        float64
 86   mths_since_recent_bc_dlq                    float64
 87   mths_since_recent_inq                       float64
 88   mths_since_recent_revol_delinq              float64
 89   num_accts_ever_120_pd                       float64
 90   num_actv_bc_tl                              float64
 91   num_actv_rev_tl                             float64
 92   num_bc_sats                                 float64
 93   num_bc_tl                                   float64
 94   num_il_tl                                   float64
 95   num_op_rev_tl                               float64
 96   num_rev_accts                               float64
 97   num_rev_tl_bal_gt_0                         float64
 98   num_sats                                    float64
 99   num_tl_120dpd_2m                            float64
 100  num_tl_30dpd                                float64
 101  num_tl_90g_dpd_24m                          float64
 102  num_tl_op_past_12m                          float64
 103  pct_tl_nvr_dlq                              float64
 104  percent_bc_gt_75                            float64
 105  pub_rec_bankruptcies                        float64
 106  tax_liens                                   float64
 107  tot_hi_cred_lim                             float64
 108  total_bal_ex_mort                           float64
 109  total_bc_limit                              float64
 110  total_il_high_credit_limit                  float64
 111  revol_bal_joint                             float64
 112  sec_app_earliest_cr_line                    object
 113  sec_app_inq_last_6mths                      float64
 114  sec_app_mort_acc                            float64
 115  sec_app_open_acc                            float64
 116  sec_app_revol_util                          float64
 117  sec_app_open_act_il                         float64
 118  sec_app_num_rev_accts                       float64
 119  sec_app_chargeoff_within_12_mths            float64
 120  sec_app_collections_12_mths_ex_med          float64
 121  sec_app_mths_since_last_major_derog         float64
 122  hardship_flag                               object
 123  hardship_type                               object
 124  hardship_reason                             object
 125  hardship_status                             object
 126  deferral_term                               float64
 127  hardship_amount                             float64
 128  hardship_start_date                         object
 129  hardship_end_date                           object
 130  payment_plan_start_date                     object
 131  hardship_length                             float64
 132  hardship_dpd                                float64
 133  hardship_loan_status                        object
 134  orig_projected_additional_accrued_interest  float64
 135  hardship_payoff_balance_amount              float64
 136  hardship_last_payment_amount                float64
 137  disbursement_method                         object
 138  debt_settlement_flag                        object
 139  debt_settlement_flag_date                   object
 140  settlement_status                           object
 141  settlement_date                             object
 142  settlement_amount                           float64
 143  settlement_percentage                       float64
 144  settlement_term                             float64
dtypes: float64(105), int64(4), object(36)
memory usage: 2.4+ GB

In [6]:
loandf.describe()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,url,dti,...,deferral_term,hardship_amount,hardship_length,hardship_dpd,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,settlement_amount,settlement_percentage,settlement_term
count,0.0,0.0,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260664e+06,0.0,2.258957e+06,...,10613.0,10613.000000,10613.0,10613.000000,8426.000000,10613.000000,10613.000000,33056.000000,33056.000000,33056.000000
mean,NaN,NaN,1.504693e+04,1.504166e+04,1.502344e+04,1.309291e+01,4.458076e+02,7.799243e+04,NaN,1.882420e+01,...,3.0,155.006696,3.0,13.686422,454.840802,11628.036442,193.606331,5030.606922,47.775600,13.148596
std,NaN,NaN,9.190245e+03,9.188413e+03,9.192332e+03,4.832114e+00,2.671737e+02,1.126962e+05,NaN,1.418333e+01,...,0.0,129.113137,0.0,9.728138,375.830737,7615.161123,198.694368,3692.027842,7.336379,8.192319
min,NaN,NaN,5.000000e+02,5.000000e+02,0.000000e+00,5.310000e+00,4.930000e+00,0.000000e+00,NaN,-1.000000e+00,...,3.0,0.640000,3.0,0.000000,1.920000,55.730000,0.010000,44.210000,0.200000,0.000000
25%,NaN,NaN,8.000000e+03,8.000000e+03,8.000000e+03,9.490000e+00,2.516500e+02,4.600000e+04,NaN,1.189000e+01,...,3.0,59.370000,3.0,5.000000,174.967500,5628.730000,43.780000,2227.000000,45.000000,6.000000
50%,NaN,NaN,1.290000e+04,1.287500e+04,1.280000e+04,1.262000e+01,3.779900e+02,6.500000e+04,NaN,1.784000e+01,...,3.0,119.040000,3.0,15.000000,352.605000,10044.220000,132.890000,4172.855000,45.000000,14.000000
75%,NaN,NaN,2.000000e+04,2.000000e+04,2.000000e+04,1.599000e+01,5.933200e+02,9.300000e+04,NaN,2.449000e+01,...,3.0,213.260000,3.0,22.000000,622.792500,16114.940000,284.180000,6870.782500,50.000000,18.000000
max,NaN,NaN,4.000000e+04,4.000000e+04,4.000000e+04,3.099000e+01,1.719830e+03,1.100000e+08,NaN,9.990000e+02,...,3.0,943.940000,3.0,37.000000,2680.890000,40306.410000,1407.860000,33601.000000,521.350000,181.000000

In [ ]:
#sns.pairplot(autodf[['mpg','displacement','horsepower','weight','acceleration','year']])
#explore for specific variables.